#ifndef _GENERATE_PARALLEL_RESULT_H_
#define _GENERATE_PARALLEL_RESULT_H_

enum GENERATE_PARALLEL_RESULT {
	GENERATE_PARALLEL_RESULT_NONE,
	GENERATE_PARALLEL_RESULT_NO_FIND,
	GENERATE_PARALLEL_RESULT_FINDED,
	GENERATE_PARALLEL_RESULT_COMPLETED,
};

#endif