#ifndef _SYNTAX_NODE_TYPE_H_
#define _SYNTAX_NODE_TYPE_H_

enum SYNTAX_NODE_TYPE {
	SYNTAX_NODE_TYPE_NONE,
	SYNTAX_NODE_TYPE_NUMBER,
	SYNTAX_NODE_TYPE_STRING,
	SYNTAX_NODE_TYPE_ADD,
	SYNTAX_NODE_TYPE_SUB,
	SYNTAX_NODE_TYPE_MUL,
	SYNTAX_NODE_TYPE_DIV,
	SYNTAX_NODE_TYPE_MOD,
	SYNTAX_NODE_TYPE_AND,
	SYNTAX_NODE_TYPE_OR,
	SYNTAX_NODE_TYPE_NOT,
	SYNTAX_NODE_TYPE_INC,
	SYNTAX_NODE_TYPE_ASSIGNMENT,
	SYNTAX_NODE_TYPE_VARIABLE,
	SYNTAX_NODE_TYPE_FOR,
	SYNTAX_NODE_TYPE_PROC_DEF,
	SYNTAX_NODE_TYPE_PROC_CALL,
	SYNTAX_NODE_TYPE_RETURN,
	SYNTAX_NODE_TYPE_SCOPE,
	SYNTAX_NODE_TYPE_ENUM_DEF,
	SYNTAX_NODE_TYPE_STRUCT_DEF,
	SYNTAX_NODE_TYPE_UNION_DEF
};

#endif